Update reference to deprecated constant
Otherwise build fails:

    FAILED: gtkgreet/gtkgreet.p/gtkgreet.c.o
    cc -Igtkgreet/gtkgreet.p -Igtkgreet -I../gtkgreet/gtkgreet -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/json-c -I/usr/include/gtk-layer-shell -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -Wno-unused-parameter -Wno-missing-braces -DLAYER_SHELL -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIE -pthread -MD -MQ gtkgreet/gtkgreet.p/gtkgreet.c.o -MF gtkgreet/gtkgreet.p/gtkgreet.c.o.d -o gtkgreet/gtkgreet.p/gtkgreet.c.o -c ../gtkgreet/gtkgreet/gtkgreet.c
    ../gtkgreet/gtkgreet/gtkgreet.c: In function ‘create_gtkgreet’:
    ../gtkgreet/gtkgreet/gtkgreet.c:94:5: error: ‘G_APPLICATION_FLAGS_NONE’ is deprecated: Use 'G_APPLICATION_DEFAULT_FLAGS' instead [-Werror=deprecated-declarations]
       94 |     gtkgreet->app = gtk_application_new("wtf.kl.gtkgreet", G_APPLICATION_FLAGS_NONE);
          |     ^~~~~~~~
    In file included from /usr/include/glib-2.0/gio/giotypes.h:30,
                     from /usr/include/glib-2.0/gio/gio.h:28,
                     from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                     from /usr/include/gtk-3.0/gdk/gdk.h:32,
                     from /usr/include/gtk-3.0/gtk/gtk.h:30,
                     from ../gtkgreet/gtkgreet/gtkgreet.c:3:
    /usr/include/glib-2.0/gio/gioenums.h:1536:3: note: declared here
     1536 |   G_APPLICATION_FLAGS_NONE GLIB_DEPRECATED_ENUMERATOR_IN_2_74_FOR(G_APPLICATION_DEFAULT_FLAGS),
          |   ^~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    ninja: build stopped: subcommand failed.